### ISSUE TITLE
Missing Localization within toArray()

### ISSUE THREAD

**Issue by sirthxalot** [BenSampo/laravel-enum#38]
Hi Ben!

Its me again (@sirthxalot) - don't worry I don't want to blow up your issue tracker nor the source code but I have found two improvements, which I would like to discuss with you. I will open the requests separately in order to keep everything isolated.

## Background

My first improvement will be the `toArray()` method. When using the method in combination with localized enums the translations are missing. This is because there is no `getDescription()` method within `toArray()` on the other hand you implemented the localization within `toSelectArray()` (https://github.com/BenSampo/laravel-enum/blob/master/src/Enum.php#L153). So why don't we extract that to the `toArray()` method so both arrays will be translated? 

## Questions

Due the code review I was wondering how you cache the array there is a `$constantCacheArray` property filled by the `getConstants()` method, but when we translate the `toArray()` array method these properties will not be updated. How should we handle this?

Another question I had: 
> Is there any reason to return the array without localization?

I think the answer is "no". So should we add a parameter to disable localization, e.g. `toArray($localized = true)`.

And last but not least: If you are translating the values of the enum you will propeply expecting a sorted array. So in my opionion there should be another parameter to determine the sorting.

## Example

Hope you will get the points. The final method propably will look like the following:

```php
    /**
     * Return the enum as an array.
     * 
     * @param boolean $localized
     * A boolean that determine whether if the values should be translated (`true`) 
     * or not (`false`). Default is: `true`.
     *
     * @param boolean $sorting
     * A boolean that determine whether if the sorting is enabled (`true`) 
     * or not (`false`). Default is: `true`.
     *  
     * @return array
     */
    public static function toArray($localized = true, $sorting = true): array
    {
        $constants = static::getConstants();
        $array = [];

        foreach ($constants as $key => $value) {
            if (true === $localized) {
                $array[$key] = static::getDescription($value);
            } else {
                $array[$key] = $value;
            }
        }

        if (true === $sorting) {
            asort($array);
        }

        return $array;
    }
```

## Tasks

- [ ] Update `BenSampo\Enum::toArray()` method.
- [ ] Update `README.md`
- [ ] Add tests `BenSampo\Enum\Tests\EnumLocalizationTest` (may other test will be affected by this)?

## Contribute

**Branch**: `master`  
**Version**: 1.17.1  
**Release Date**: 24. Decembre 2018 _(My xmas present for you ;)_

> **Feedback**: «your feedback is welcome here»

- [ ] Please check if I can create a pull request for this.

Best regards

Alexander Bösch

**Comment by BenSampo** [comment]
Hello again @sirthxalot. Really appreciate the effort and thought you've put into these issues, thank you 👍 I like the idea behind this one, but would like to approach it slightly differently.

I'm slightly apprehensive about modifying the `toArray` method, since it's a representation of a traditional enum as an array, which would just be the key/value pair. The description, and therefore the translation element, I see as extra polish on top of this. It would also be a breaking change if we start modifying the output of the `toArray` method, which I'd like to avoid if possible.

I think the use case between the `toArray` method and what you're looking to achieve is slightly different. I wonder if the feature you're suggesting deserves its own method, perhaps returning the enum as a [`Collection`](https://laravel.com/docs/5.7/collections). 

I'm thinking you could call a `asCollection` method on an enum which returns a `Collection` of `EnumItem` objects (a new class) which each have a `key`, `value` and `description` property. Example below.

```php
// Example enum
final class UserType extends Enum
{
    const Administrator = 0;
    const Moderator = 1;
    const Subscriber = 2;
}

// Gabbing the enum as a collection and then iterating over it
UserType::asCollection()->map(function(EnumItem $userType) {
    $userType->key; // e.g. Administrator
    $userType->value; // e.g. 0
    $userType->description; // e.g. Administrator (translated)
});
```

This gives a nice API for working with an enum as an iterable object, and thanks to Laravel's awesome `Collection` features, opens up the possibility for sorting, filtering and all that good stuff without it having to be implemented in this library.

What do you reckon?

**Comment by sirthxalot** [comment]
Hi Ben!

Thank you for your reply.

Ok now I see the reason:

>  it's a representation of a traditional enum as an array, which would just be the key/value pair.

And I agree with this comment - we need a way to work with the plain keys and values. However I would recommend to make the translation process easier for us. So the easiest way to make both of us happy would be to changing the default parameters to `false` than - the current implementation will have no side affects and the user can determine whether if he wants to get the translated strings or not.

Would this satisfy our imagination of a perfect Enum package?

The implementation will look the same as mentioned above (https://github.com/BenSampo/laravel-enum/issues/38#issue-393198992) but with different default parameters. Maybe I didn't point out that I would like to move the impelmentation of `toSelectArray` into `toArray` so the final code may look like the following: 

```php
    /**
     * Return the enum as an array.
     * 
     * @param boolean $localized
     * A boolean that determine whether if the values should be translated (`true`) 
     * or not (`false`). Default is: `false`.
     *
     * @param boolean $sorting
     * A boolean that determine whether if the sorting is enabled (`true`) 
     * or not (`false`). Default is: `false`.
     *  
     * @return array
     */
    public static function toArray($localized = false, $sorting = false): array
    {
        $constants = static::getConstants();
        $array = [];

        foreach ($constants as $key => $value) {
            if (true === $localized) {
                $array[$key] = static::getDescription($value);
            } else {
                $array[$key] = $value;
            }
        }

        if (true === $sorting) {
            asort($array);
        }

        return $array;
    }
```

And the `toSelectArray`:

```php
    public static function toSelectArray(): array
    {
        return self::toArray(true, false);
    }
```

best regards

Alexander Bösch

## Tasks

- [ ] Update `BenSampo\Enum::toArray()` method.
- [ ] Update `BenSampo\Enum::toSelectArray()` method.
- [ ] Update `README.md`
- [ ] Add tests `BenSampo\Enum\Tests\EnumLocalizationTest` (may other test will be affected by this)?

## Contribute

**Branch**: `master`  
**Version**: 1.17.1  
**Release Date**: 24. Decembre 2018 _(My xmas present for you ;)_

- [ ] I agree you are good to go!
