### ISSUE TITLE
Enum to Option List

### ISSUE THREAD

**Issue by sirthxalot** [BenSampo/laravel-enum#39]
Hi Ben!

When I was using your package I was missing a to options list. Usually if you work with enums you will get to a point where you may need to create a select field. For now we need to create the HTML by ourselves but how about a method that returns the options as HTML tags.

I don't want to implement a select field since the configuration for can be too heavy (e.g. readonly, required attributes and so on). Instead I want to have a list with options. So why don't we implement a `toOptions()` method which will render the option list.

So how do I imagine how we should create a select field:

```php
            <select name="countries" id="i-countries">
                <option value="">{{ __('** Please choose **') }}</option>
                {!! App\Enums\Countries::toOptions() !!}
            </select>
```

So `App\Enums\Countries::toOptions([$key])` will generate something like this:

```php
<option value="$key" selected="selected">$value</option>
```

May you wonder why we pass in an array? This attribute determines an array of selected options and it will expecting the keys. So if we find the key within our enum we will flag it as selected - an array is helpful if you would like to use multiselect fields.

## Example

A possible implementation will be:

```php
    /**
     * Return the enum as a HTML option list.
     * 
     * @param array $selected
     * An array that list the keys that will have the `selected` attribute.
     *  
     * @return string
     */
    public static function toOptions($selected = []): string
    {
        $html = '';
        $data = static::toArray();

        foreach($data as $key => $value) {
            $html .= '<option value="';
            $html .= $key;
            $html .= '"';
            if (array_key_exists($key, $selected)) {
                $html .= ' selected="selected"';
            }
            $html .= '>';
            $html .= $value;
            $html .= '</option>'
        }

        return $html;
    }
```

What do you think about this? One question I had is: Do we need an implentation to use the `toSelectArray()` instead of `toArray()`? I don't think so.

## Tasks

- [ ] Add `BenSampo\Enum::toOptions()` method.
- [ ] Update `README.md`
- [ ] Add tests `BenSampo\Enum\Tests\HtmlRender` (agree with the naming convention)?

## Contribute

**Branch**: `master`  
**Version**: 1.18.1 or 1.17.1 (depend on answer at #38).  
**Release Date**: 24. Decembre 2018 _(My xmas present for you ;)_

> **Feedback**: «your feedback is welcome here»

- [ ] Please check if I can create a pull request for this.

Best regards

Alexander Bösch
